//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace mytemplate.Model
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class MyTemplateEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new MyTemplateEntities object using the connection string found in the 'MyTemplateEntities' section of the application configuration file.
        /// </summary>
        public MyTemplateEntities() : base("name=MyTemplateEntities", "MyTemplateEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new MyTemplateEntities object.
        /// </summary>
        public MyTemplateEntities(string connectionString) : base(connectionString, "MyTemplateEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new MyTemplateEntities object.
        /// </summary>
        public MyTemplateEntities(EntityConnection connection) : base(connection, "MyTemplateEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Comment> Comment
        {
            get
            {
                if ((_Comment == null))
                {
                    _Comment = base.CreateObjectSet<Comment>("Comment");
                }
                return _Comment;
            }
        }
        private ObjectSet<Comment> _Comment;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Feedback> Feedback
        {
            get
            {
                if ((_Feedback == null))
                {
                    _Feedback = base.CreateObjectSet<Feedback>("Feedback");
                }
                return _Feedback;
            }
        }
        private ObjectSet<Feedback> _Feedback;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Comment EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToComment(Comment comment)
        {
            base.AddObject("Comment", comment);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Feedback EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToFeedback(Feedback feedback)
        {
            base.AddObject("Feedback", feedback);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MyTemplateModel", Name="Comment")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Comment : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Comment object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="commentText">Initial value of the CommentText property.</param>
        /// <param name="entityId">Initial value of the EntityId property.</param>
        /// <param name="entityType">Initial value of the EntityType property.</param>
        /// <param name="submitDate">Initial value of the SubmitDate property.</param>
        /// <param name="submitterName">Initial value of the SubmitterName property.</param>
        /// <param name="submitterEmail">Initial value of the SubmitterEmail property.</param>
        /// <param name="milestone">Initial value of the Milestone property.</param>
        public static Comment CreateComment(global::System.Int32 id, global::System.String commentText, global::System.Int32 entityId, global::System.Int32 entityType, global::System.DateTime submitDate, global::System.String submitterName, global::System.String submitterEmail, global::System.String milestone)
        {
            Comment comment = new Comment();
            comment.Id = id;
            comment.CommentText = commentText;
            comment.EntityId = entityId;
            comment.EntityType = entityType;
            comment.SubmitDate = submitDate;
            comment.SubmitterName = submitterName;
            comment.SubmitterEmail = submitterEmail;
            comment.Milestone = milestone;
            return comment;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CommentText
        {
            get
            {
                return _CommentText;
            }
            set
            {
                OnCommentTextChanging(value);
                ReportPropertyChanging("CommentText");
                _CommentText = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CommentText");
                OnCommentTextChanged();
            }
        }
        private global::System.String _CommentText;
        partial void OnCommentTextChanging(global::System.String value);
        partial void OnCommentTextChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 EntityId
        {
            get
            {
                return _EntityId;
            }
            set
            {
                OnEntityIdChanging(value);
                ReportPropertyChanging("EntityId");
                _EntityId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EntityId");
                OnEntityIdChanged();
            }
        }
        private global::System.Int32 _EntityId;
        partial void OnEntityIdChanging(global::System.Int32 value);
        partial void OnEntityIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 EntityType
        {
            get
            {
                return _EntityType;
            }
            set
            {
                OnEntityTypeChanging(value);
                ReportPropertyChanging("EntityType");
                _EntityType = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EntityType");
                OnEntityTypeChanged();
            }
        }
        private global::System.Int32 _EntityType;
        partial void OnEntityTypeChanging(global::System.Int32 value);
        partial void OnEntityTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime SubmitDate
        {
            get
            {
                return _SubmitDate;
            }
            set
            {
                OnSubmitDateChanging(value);
                ReportPropertyChanging("SubmitDate");
                _SubmitDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SubmitDate");
                OnSubmitDateChanged();
            }
        }
        private global::System.DateTime _SubmitDate;
        partial void OnSubmitDateChanging(global::System.DateTime value);
        partial void OnSubmitDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SubmitterName
        {
            get
            {
                return _SubmitterName;
            }
            set
            {
                OnSubmitterNameChanging(value);
                ReportPropertyChanging("SubmitterName");
                _SubmitterName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("SubmitterName");
                OnSubmitterNameChanged();
            }
        }
        private global::System.String _SubmitterName;
        partial void OnSubmitterNameChanging(global::System.String value);
        partial void OnSubmitterNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SubmitterEmail
        {
            get
            {
                return _SubmitterEmail;
            }
            set
            {
                OnSubmitterEmailChanging(value);
                ReportPropertyChanging("SubmitterEmail");
                _SubmitterEmail = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("SubmitterEmail");
                OnSubmitterEmailChanged();
            }
        }
        private global::System.String _SubmitterEmail;
        partial void OnSubmitterEmailChanging(global::System.String value);
        partial void OnSubmitterEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SubmitterWebsite
        {
            get
            {
                return _SubmitterWebsite;
            }
            set
            {
                OnSubmitterWebsiteChanging(value);
                ReportPropertyChanging("SubmitterWebsite");
                _SubmitterWebsite = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SubmitterWebsite");
                OnSubmitterWebsiteChanged();
            }
        }
        private global::System.String _SubmitterWebsite;
        partial void OnSubmitterWebsiteChanging(global::System.String value);
        partial void OnSubmitterWebsiteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CreatedBy
        {
            get
            {
                return _CreatedBy;
            }
            set
            {
                OnCreatedByChanging(value);
                ReportPropertyChanging("CreatedBy");
                _CreatedBy = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CreatedBy");
                OnCreatedByChanged();
            }
        }
        private global::System.String _CreatedBy;
        partial void OnCreatedByChanging(global::System.String value);
        partial void OnCreatedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> CreatedOn
        {
            get
            {
                return _CreatedOn;
            }
            set
            {
                OnCreatedOnChanging(value);
                ReportPropertyChanging("CreatedOn");
                _CreatedOn = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreatedOn");
                OnCreatedOnChanged();
            }
        }
        private Nullable<global::System.DateTime> _CreatedOn;
        partial void OnCreatedOnChanging(Nullable<global::System.DateTime> value);
        partial void OnCreatedOnChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LastModeratedBy
        {
            get
            {
                return _LastModeratedBy;
            }
            set
            {
                OnLastModeratedByChanging(value);
                ReportPropertyChanging("LastModeratedBy");
                _LastModeratedBy = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LastModeratedBy");
                OnLastModeratedByChanged();
            }
        }
        private global::System.String _LastModeratedBy;
        partial void OnLastModeratedByChanging(global::System.String value);
        partial void OnLastModeratedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> LastModeratedOn
        {
            get
            {
                return _LastModeratedOn;
            }
            set
            {
                OnLastModeratedOnChanging(value);
                ReportPropertyChanging("LastModeratedOn");
                _LastModeratedOn = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastModeratedOn");
                OnLastModeratedOnChanged();
            }
        }
        private Nullable<global::System.DateTime> _LastModeratedOn;
        partial void OnLastModeratedOnChanging(Nullable<global::System.DateTime> value);
        partial void OnLastModeratedOnChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Milestone
        {
            get
            {
                return _Milestone;
            }
            set
            {
                OnMilestoneChanging(value);
                ReportPropertyChanging("Milestone");
                _Milestone = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Milestone");
                OnMilestoneChanged();
            }
        }
        private global::System.String _Milestone;
        partial void OnMilestoneChanging(global::System.String value);
        partial void OnMilestoneChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MyTemplateModel", Name="Feedback")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Feedback : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Feedback object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="city">Initial value of the City property.</param>
        /// <param name="emailAddress">Initial value of the EmailAddress property.</param>
        public static Feedback CreateFeedback(global::System.Int32 id, global::System.String name, global::System.String city, global::System.String emailAddress)
        {
            Feedback feedback = new Feedback();
            feedback.Id = id;
            feedback.Name = name;
            feedback.City = city;
            feedback.EmailAddress = emailAddress;
            return feedback;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String City
        {
            get
            {
                return _City;
            }
            set
            {
                OnCityChanging(value);
                ReportPropertyChanging("City");
                _City = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("City");
                OnCityChanged();
            }
        }
        private global::System.String _City;
        partial void OnCityChanging(global::System.String value);
        partial void OnCityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String EmailAddress
        {
            get
            {
                return _EmailAddress;
            }
            set
            {
                OnEmailAddressChanging(value);
                ReportPropertyChanging("EmailAddress");
                _EmailAddress = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("EmailAddress");
                OnEmailAddressChanged();
            }
        }
        private global::System.String _EmailAddress;
        partial void OnEmailAddressChanging(global::System.String value);
        partial void OnEmailAddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ContactNo
        {
            get
            {
                return _ContactNo;
            }
            set
            {
                OnContactNoChanging(value);
                ReportPropertyChanging("ContactNo");
                _ContactNo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ContactNo");
                OnContactNoChanged();
            }
        }
        private global::System.String _ContactNo;
        partial void OnContactNoChanging(global::System.String value);
        partial void OnContactNoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String OverallExperience
        {
            get
            {
                return _OverallExperience;
            }
            set
            {
                OnOverallExperienceChanging(value);
                ReportPropertyChanging("OverallExperience");
                _OverallExperience = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("OverallExperience");
                OnOverallExperienceChanged();
            }
        }
        private global::System.String _OverallExperience;
        partial void OnOverallExperienceChanging(global::System.String value);
        partial void OnOverallExperienceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DissatisfiedWith
        {
            get
            {
                return _DissatisfiedWith;
            }
            set
            {
                OnDissatisfiedWithChanging(value);
                ReportPropertyChanging("DissatisfiedWith");
                _DissatisfiedWith = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DissatisfiedWith");
                OnDissatisfiedWithChanged();
            }
        }
        private global::System.String _DissatisfiedWith;
        partial void OnDissatisfiedWithChanging(global::System.String value);
        partial void OnDissatisfiedWithChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CorrectIt
        {
            get
            {
                return _CorrectIt;
            }
            set
            {
                OnCorrectItChanging(value);
                ReportPropertyChanging("CorrectIt");
                _CorrectIt = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CorrectIt");
                OnCorrectItChanged();
            }
        }
        private global::System.String _CorrectIt;
        partial void OnCorrectItChanging(global::System.String value);
        partial void OnCorrectItChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Rating
        {
            get
            {
                return _Rating;
            }
            set
            {
                OnRatingChanging(value);
                ReportPropertyChanging("Rating");
                _Rating = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Rating");
                OnRatingChanged();
            }
        }
        private global::System.String _Rating;
        partial void OnRatingChanging(global::System.String value);
        partial void OnRatingChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String WebsiteComparison
        {
            get
            {
                return _WebsiteComparison;
            }
            set
            {
                OnWebsiteComparisonChanging(value);
                ReportPropertyChanging("WebsiteComparison");
                _WebsiteComparison = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("WebsiteComparison");
                OnWebsiteComparisonChanged();
            }
        }
        private global::System.String _WebsiteComparison;
        partial void OnWebsiteComparisonChanging(global::System.String value);
        partial void OnWebsiteComparisonChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Suggestions
        {
            get
            {
                return _Suggestions;
            }
            set
            {
                OnSuggestionsChanging(value);
                ReportPropertyChanging("Suggestions");
                _Suggestions = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Suggestions");
                OnSuggestionsChanged();
            }
        }
        private global::System.String _Suggestions;
        partial void OnSuggestionsChanging(global::System.String value);
        partial void OnSuggestionsChanged();

        #endregion

    
    }

    #endregion

    
}
